DROP EVENT `e_hourly`//
CREATE DEFINER=`vidaprint`@`%` EVENT `e_hourly` ON SCHEDULE EVERY 1 HOUR STARTS '2013-02-07 16:05:00' ON COMPLETION NOT PRESERVE ENABLE COMMENT 'sum data' DO CALL vida_runhourly()


DROP EVENT `e_daily`//
CREATE DEFINER=`vidaprint`@`%` EVENT `e_daily` ON SCHEDULE EVERY 1 DAY STARTS '2013-02-17 01:00:00' ON COMPLETION NOT PRESERVE ENABLE COMMENT 'sum data' DO CALL vida_rundaily()


DROP EVENT `e_monthly`//
CREATE DEFINER=`vidaprint`@`%` EVENT `e_monthly` ON SCHEDULE EVERY 1 MONTH STARTS '2013-01-02 01:00:00' ON COMPLETION NOT PRESERVE ENABLE COMMENT 'sum data' DO CALL vida_runmonthly()

